name: Build and Deploy to CloudHub 2.0
on:
  push:
    branches: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
    - name: Show Maven version
      run: mvn -version

    - name: Deploy to Exchange
      run: mvn deploy -settings .maven/settings.xml

    - name: Deploy to CloudHub
      run: |
        mvn deploy -DmuleDeploy -settings .maven/settings.xml